version: '3.0'

services:
  server:
    container_name: server
    build:
      context: server/.
    env_file:
      - server/.production.env
    ports:
    - 5000:5000
    - 7000:7000
    volumes:
      - upload:/app/upload
    command: npm run start
    restart: always
  client:
    container_name: client
    build:
      context: client/.
    env_file:
      - client/.env.production
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - server
    restart: always
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
    - 80:80
volumes:
  upload:
